### ISSUE TITLE
想问下关于代码生成

### ISSUE THREAD

**Issue by akkuman** [groupher/groupher_web#112]
https://github.com/groupher/groupher_web/blob/dev/src/stores/RootStore/index.ts

看到这个文件注释提到是自动生成的，但似乎没找到是怎么生成的，plop 的模板好像和这个并不相同

可以告知下是怎么生成出来的吗

**Comment by mydearxym** [comment]
hi, 这个文件是通过注释占位符插入的，通过 plop 的 append 方法，请参考：

https://github.com/groupher/groupher_web/blob/dev/src/stores/RootStore/index.ts#L59
https://github.com/groupher/groupher_web/blob/dev/utils/scripts/generators/container/index.js#L107-L113
